export const affiliate = [
  {
    name: "Amazon",
    description: "",
    url: "",
    type: "order",
    category: "Shopping",
    subCategory: "Online-Shop",
    rewards: {
      referrer: "",
      user: "",
    },
    payoutOn: "",
    lastUpdated: new Date("2024-05-13"),
    blog: "",
  },
  {
    name: "Bondora",
    description: "",
    url: "",
    type: "register",
    category: "Finanzen",
    subCategory: "P2P-Kredite",
    rewards: {
      referrer: "5 Euro",
      user: "",
    },
    payoutOn: "",
    lastUpdated: new Date("2024-05-13"),
    blog: "",
  },
  {
    name: "Debitum",
    description: "",
    url: "",
    type: "register",
    category: "Finanzen",
    subCategory: "P2P-Kredite",
    rewards: {
      referrer: "",
      user: "",
    },
    payoutOn: "",
    lastUpdated: new Date("2024-05-13"),
    blog: "",
  },
  {
    name: "Flatex",
    description: "",
    url: "",
    type: "register",
    category: "Finanzen",
    subCategory: "Broker",
    rewards: {
      referrer: "",
      user: "",
    },
    payoutOn: "",
    lastUpdated: new Date("2024-05-13"),
    blog: "",
  },
  {
    name: "Interactive Brokers",
    description: "",
    url: "https://ibkr.com/referral/daniel471",
    type: "register",
    category: "Finanzen",
    subCategory: "Broker",
    rewards: {
      referrer: "",
      user: "",
    },
    payoutOn: "",
    lastUpdated: new Date("2025-03-07"),
    blog: "",
  },
  {
    name: "Lande",
    description: "",
    url: "https://lande.finance?referral=F7QGGIB",
    type: "register",
    category: "Finanzen",
    subCategory: "P2P-Kredite",
    rewards: {
      referrer: "",
      user: "",
    },
    payoutOn: "",
    lastUpdated: new Date("2024-05-13"),
    blog: "",
  },
  {
    name: "Mintos",
    description: "",
    url: "",
    type: "register",
    category: "Finanzen",
    subCategory: "P2P-Kredite",
    rewards: {
      referrer: "",
      user: "",
    },
    payoutOn: "",
    lastUpdated: new Date("2024-05-13"),
    blog: "",
  },
  {
    name: "Robocash",
    description: "",
    url: "",
    type: "register",
    category: "Finanzen",
    subCategory: "P2P-Kredite",
    rewards: {
      referrer: "",
      user: "",
    },
    payoutOn: "",
    lastUpdated: new Date("2024-05-13"),
    blog: "",
  },
  {
    name: "Swaper",
    description: "",
    url: "",
    type: "register",
    category: "Finanzen",
    subCategory: "P2P-Kredite",
    rewards: {
      referrer: "",
      user: "",
    },
    payoutOn: "",
    lastUpdated: new Date("2024-05-13"),
    blog: "",
  },
  {
    name: "TickTick",
    description:
      "Organisiere dein Leben und steigere deine Produktivität mit dieser vielseitigen To-Do-App. Erstelle Aufgaben, Gewohnheiten und Erinnerungen und verfolge deine Fortschritte mit intuitiven Tools.",
    url: "https://ticktick.com/r?c=t0b238or",
    type: "register",
    category: "Produktivität",
    subCategory: "Todo-App",
    rewards: {
      referrer: "1 Monat TickTick-Premium gratis (ca.&nbsp;3&nbsp;Euro)",
      user: "leider z.Zt. nüscht...",
    },
    payoutOn: "Buchung einer Premium-Mitgliedschaft durch den Geworbenen.",
    lastUpdated: new Date("2024-05-13"),
    blog: "",
  },
  {
    name: "Trade Republic",
    description:
      "Schneller Zugang zu Handel und Sparplänen von Aktien, ETFs und Kryptos. Einfaches, provisionsfreies Investieren Made in Germany.",
    url: "https://ref.trade.re/7g7k9z1g",
    type: "register",
    category: "Finanzen",
    subCategory: "Broker",
    rewards: {
      referrer: "15 Euro",
      user: "leider z.Zt. nüscht...",
    },
    payoutOn:
      "Investition des Geworbenen innerhalb der ersten 21 Tage nach Kontoeröffung.",
    lastUpdated: new Date("2025-03-07"),
    blog: "",
  },
  {
    name: "Twino",
    description: "",
    url: "",
    type: "register",
    category: "Finanzen",
    subCategory: "P2P-Kredite",
    rewards: {
      referrer: "",
      user: "",
    },
    payoutOn: "",
    lastUpdated: new Date("2024-05-13"),
    blog: "",
  },
] as const;

export type AffiliateLink = (typeof affiliate)[number];
