export const affiliate = [
  {
    name: "Amazon",
    description: "",
    url: "",
    type: "order",
    category: "Shopping",
    subCategory: "Online-Shop",
    rewards: {
      referrer: "",
      user: "",
    },
    payoutOn: "",
    lastUpdated: new Date("2024-05-13"),
    blog: "",
  },
  {
    name: "Bondora",
    description: "",
    url: "https://bondora.com/ref/danielk39",
    type: "register",
    category: "Finanzen",
    subCategory: "P2P-Kredite",
    rewards: {
      referrer: "5 Euro",
      user: "5 Euro",
    },
    payoutOn: "nach 90 Tagen",
    lastUpdated: new Date("2025-03-24"),
    blog: "",
  },
  {
    name: "Debitum",
    description: "",
    url: "https://debitum.investments/en/r/PRU4I",
    type: "register",
    category: "Finanzen",
    subCategory: "P2P-Kredite",
    rewards: {
      referrer: "1-2,5% der investierten Summe in den ersten 30 Tage",
      user: "1-2,5% der investierten Summe in den ersten 30 Tagen",
    },
    payoutOn:
      "Sofort. Für jede Investition von 10 Euro oder mehr, die innerhalb von 30 Tagen nach der Registrierung getätigt wird.<br>" +
      "<b>Beispiel:</b><br>" +
      '"Wenn Ihr Freund 5000 EUR investiert, erhalten Sie beide einen Bonus von 2,5% für 1000 EUR + 1% für den Restbetrag.<br>' +
      '(25 EUR + 1% von den verbleibenden 4000 EUR) = 65 EUR"',
    lastUpdated: new Date("2024-05-13"),
    blog: "",
  },
  {
    name: "Flatex",
    description: "",
    url: "",
    type: "register",
    category: "Finanzen",
    subCategory: "Broker",
    rewards: {
      referrer: "",
      user: "",
    },
    payoutOn: "",
    lastUpdated: new Date("2024-05-13"),
    blog: "",
  },
  {
    name: "Interactive Brokers",
    description: "",
    url: "https://ibkr.com/referral/daniel471",
    type: "register",
    category: "Finanzen",
    subCategory: "Broker",
    rewards: {
      referrer: "",
      user: "",
    },
    payoutOn: "",
    lastUpdated: new Date("2025-03-07"),
    blog: "",
  },
  {
    name: "Lande",
    description: "",
    url: "https://lande.finance?referral=F7QGGIB",
    type: "register",
    category: "Finanzen",
    subCategory: "P2P-Kredite",
    rewards: {
      referrer: "",
      user: "",
    },
    payoutOn: "",
    lastUpdated: new Date("2024-05-13"),
    blog: "",
  },
  {
    name: "Mintos",
    description: "",
    url: "https://www.mintos.com/de/l/ref/IH3ANU",
    type: "register",
    category: "Finanzen",
    subCategory: "P2P-Kredite",
    rewards: {
      referrer: "50 Euro",
      user: "50 Euro<br>+1% Bonus auf die durchschnittliche Investiion in den ersten 90 Tagen",
    },
    payoutOn:
      "Wenn der Geworbene mind. 1.000 Euro innerhalb von 60 Tagen nach der Registrierung investiert und bis zum 90. Tag nach der Registrierung mind. 1.000 Euro aufrechterhält.",
    lastUpdated: new Date("2025-03-24"),
    blog: "",
  },
  {
    name: "Robocash",
    description: "",
    url: "",
    type: "register",
    category: "Finanzen",
    subCategory: "P2P-Kredite",
    rewards: {
      referrer: "",
      user: "",
    },
    payoutOn: "",
    lastUpdated: new Date("2024-05-13"),
    blog: "",
  },
  {
    name: "Swaper",
    description: "",
    url: "",
    type: "register",
    category: "Finanzen",
    subCategory: "P2P-Kredite",
    rewards: {
      referrer: "",
      user: "",
    },
    payoutOn: "",
    lastUpdated: new Date("2024-05-13"),
    blog: "",
  },
  {
    name: "TickTick",
    description:
      "Organisiere dein Leben und steigere deine Produktivität mit dieser vielseitigen To-Do-App. Erstelle Aufgaben, Gewohnheiten und Erinnerungen und verfolge deine Fortschritte mit intuitiven Tools.",
    url: "https://ticktick.com/r?c=t0b238or",
    type: "register",
    category: "Produktivität",
    subCategory: "Todo-App",
    rewards: {
      referrer: "1 Monat TickTick-Premium gratis (ca.&nbsp;3&nbsp;Euro)",
      user: "leider z.Zt. nüscht...",
    },
    payoutOn: "Buchung einer Premium-Mitgliedschaft durch den Geworbenen.",
    lastUpdated: new Date("2024-05-13"),
    blog: "",
  },
  {
    name: "Trade Republic",
    description:
      "Schneller Zugang zu Handel und Sparplänen von Aktien, ETFs und Kryptos. Einfaches, provisionsfreies Investieren Made in Germany.",
    url: "https://ref.trade.re/7g7k9z1g",
    type: "register",
    category: "Finanzen",
    subCategory: "Broker",
    rewards: {
      referrer: "15 Euro",
      user: "leider z.Zt. nüscht...",
    },
    payoutOn:
      "Investition des Geworbenen innerhalb der ersten 21 Tage nach Kontoeröffung.",
    lastUpdated: new Date("2025-03-07"),
    blog: "",
  },
  {
    name: "Twino",
    description: "",
    url: "",
    type: "register",
    category: "Finanzen",
    subCategory: "P2P-Kredite",
    rewards: {
      referrer: "",
      user: "",
    },
    payoutOn: "",
    lastUpdated: new Date("2024-05-13"),
    blog: "",
  },
] as const;

export type AffiliateLink = (typeof affiliate)[number];
